version: '3.8'

# Development override configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infographai_dev
      # Enable query logging for development
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_DURATION: on

  redis:
    ports:
      - "6379:6379"
    # Enable Redis monitor for debugging
    command: redis-server --appendonly yes --loglevel debug

  # Adminer for database management (Development only)
  adminer:
    image: adminer:latest
    container_name: infographai-adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  # Redis Commander for Redis management (Development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: infographai-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis